export const logo = require('./logo.jpeg')
export const logoRounded = require('./logo-rounded.png')
export const passion = require('./passion.webp')
export const roadmap_v1 = require('./roadmap-v1.svg')
export const empowering = require('./empowering.webp')
export const tokenomics_table = require('./tokenomics-table.svg')